### ISSUE TITLE
Exit code 1 on fixing imports interferes with scripts

### ISSUE THREAD

**Issue by ajyoon** [hakancelikdev/unimport#211]
I'm setting up `unimport` in a git pre-commit hook, and I was surprised to see that when `unimport` finds errors it can fix, it exits with code 1 instead of 0. This is problematic when running within a bash script that bails on error codes, for instance:

```sh
set -e
unimport --check --remove
```

If this is set as a pre-commit hook, commits will fail when fixable imports are found because the exit code 1 is interpreted as an error.

It would be helpful for such use-cases if a CLI option existed which exits 0 unless the program actually fails, like if it detects a syntax error and can't check imports at all. Otherwise it would be helpful to at least document this behavior somewhere.

**Comment by hakancelikdev** [comment]
Thanks for reporting the issue, if unimport works correctly and removes all unused imports I will change it to exit code 0.

**Comment by ajyoon** [comment]
It really depends what you think is the correct behavior. I don't know what the best practice is for CI tools commonly integrated into git hooks. Maybe it would make sense for the exit code behavior controlled by a CLI flag so this change could be done in a backwards-compatible way.

**Comment by ajyoon** [comment]
It could be the current behavior is best, and it's just a matter of documenting it.

**Comment by hakancelikdev** [comment]
No, I think the current behavior is wrong, I researched this behavior and the behavior in the new version will be as follows.

If any syntax error exists then exit code 1, if the check flag is used and there is any unused import then exit code 1, if there is any unused import and refactored file then exit code 0, for other cases exit code 1, if syntax error and unused import are not present, exit code will be 0.

**Comment by hakancelikdev** [comment]
Behavior in new version

```python

def return_exit_code(
    *,
    is_unused_modules: bool,
    check: bool,
    is_syntax_error: bool,
    refactor_applied: bool
) -> int:
    assert not (
        is_unused_modules is False and refactor_applied is True
    ), "is_unused_modules False while refactor_applied cannot be True."  # noqa

    if is_syntax_error:
        return 1
    elif is_unused_modules:
        if check:
            return 1
        elif refactor_applied:
            return 0
        return 1
    return 0

```

**Comment by ajyoon** [comment]
sounds good, thanks for looking into this!
