### ISSUE TITLE
Wrong detection for necessary import

### ISSUE THREAD

**Issue by furkanonder** [hakancelikdev/unimport#222]
I have a python file like that;
```python
import __hello__
```
when I run this file I am getting an output like that;
```sh
Hello world!
```
but ```unimport``` is saying unnecessary import in this file;
```sh
unimport test.py
__hello__ at test.py:1
````

**Comment by hakancelikdev** [comment]
You can use [skip feature](https://unimport.hakancelik.dev/tutorial/other-useful-features/#skip-import), such import statements can always happen, we don't know, they don't matter.
