### ISSUE TITLE
Error on Ubuntu with Python 3.7

### ISSUE THREAD

**Issue by ajyoon** [hakancelikdev/unimport#229]
I recently changed my project's CI from using Python 3.10 to 3.7 and unimport started failing with this error:

```
Traceback (most recent call last):
  File "/home/runner/work/neoscore/neoscore/.venv/bin/unimport", line 8, in <module>
    sys.exit(main())
  File "/home/runner/work/neoscore/neoscore/.venv/lib/python3.7/site-packages/unimport/main.py", line 60, in main
    utils.get_used_packages(Import.imports, unused_imports)
  File "/home/runner/work/neoscore/neoscore/.venv/lib/python3.7/site-packages/unimport/utils.py", line 102, in get_used_packages
    name = package_name_from_metadata(package)
  File "/home/runner/work/neoscore/neoscore/.venv/lib/python3.7/site-packages/unimport/utils.py", line 90, in package_name_from_metadata
    return metadata(package)["Name"]
  File "/home/runner/work/neoscore/neoscore/.venv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 1005, in metadata
    return Distribution.from_name(distribution_name).metadata
  File "/home/runner/work/neoscore/neoscore/.venv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 562, in from_name
    raise ValueError("A distribution name is required.")
ValueError: A distribution name is required.
```

I can't reproduce this on my local machine (Arch Linux with Python 3.7.13), but you can see detailed environment info on [the build here](https://github.com/DigiScore/neoscore/runs/7545067657?check_suite_focus=true#step:12:54).

**Comment by ajyoon** [comment]
This is happening on unimport-0.9.6 btw, which is the same version that seems to work fine on 3.10 and in my environment.

**Comment by hakancelikdev** [comment]
Thanks for letting me know, I'll work on it as soon as possible.

**Comment by hakancelikdev** [comment]
For now, to solve your problem, I can recommend you to use pre-commit, where you can define all your linters in one place and run them with Github action.


https://pre-commit.com/
https://github.com/pre-commit/action

**Comment by ajyoon** [comment]
Thank you! I could also just put the linter check in its own action which uses 3.10, I might do that since it needs the fewest changes to my workflow.

**Comment by hakancelikdev** [comment]
I think no need, you found a nice bug, Unimport has never been used before with Github action, if you wait a few days I will fix this issue.

**Comment by hakancelikdev** [comment]
Thanks for letting me know, I tested it, you can use it with GitHub action using version 0.10.0, or directly

**unimport.yml**
```
name: Unimport
on: [push, pull_request]
jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: Set up Python3.7
          uses: actions/setup-python@v2.1.4
          with:
            python-version: '3.7'
            architecture: x64
       - name: Check unused imports
         uses: hakancelikdev/unimport@0.10.0
         with:
           extra_args: --include src/
```

Let's check -> https://unimport.hakancelik.dev/#use-with-github-action

**Comment by ajyoon** [comment]
We're using a plain `pip install unimport`, so presumably this is happening on latest.

**Comment by ajyoon** [comment]
Yeah I just confirmed I'm running `0.12.2`

**Comment by hakancelikdev** [comment]
https://github.com/DigiScore/neoscore/commit/3e1d092cdc4099c7f31c418104ba28012b304e27

**Comment by ajyoon** [comment]
Running through the pre-commit framework seems to have solved the issue for us. It's possible the the user was getting an old version of unimport from before this fix.
