### ISSUE TITLE
The remove command is set to the default behavior.

### ISSUE THREAD

**Issue by hakancelikdev** [hakancelikdev/unimport#273]
When addressing this issue, we must ensure that we consider the following situations:

- [x] Unimport should remove unnecessary imports by default (current behavior, --check, now it should be --remove)
 - [x] Delete --remove related code, tests, and documentation.
 - [x] The default behavior of unimport should be documented.

https://github.com/hakancelikdev/unimport/pull/270

**Comment by hakancelikdev** [comment]
@mxr Here is the issue, If you have any questions, feel free to ask.

**Comment by mxr** [comment]
Thanks for solving this!
