### ISSUE TITLE
pre-commit autoupdate yields a weird result

### ISSUE THREAD

**Issue by isik-kaplan** [hakancelikdev/unimport#275]
```
(venv) isikkaplan@iamhere# pre-commit autoupdate
Updating https://github.com/pre-commit/pre-commit-hooks ... updating stable -> v4.4.0.
Updating https://github.com/psf/black ... updating stable -> 22.12.0.
Updating https://github.com/pycqa/isort ... updating stable -> 5.11.2.
Updating https://github.com/hakancelikdev/unimport ... updating stable -> 33ead41ee30f1d323a9c2fcfd0114297efbbc4d5.
(venv) isikkaplan@iamhere# 
```

I expected a version number but when I run autoupdate I get the `33ead41ee30f1d323a9c2fcfd0114297efbbc4d5` value for rev in my pre-commit-config file, all other hooks get a normal looking version number. 

Here is a live example from this repository. 

https://github.com/hakancelikdev/unimport/pull/268/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R15

**Comment by tolomea** [comment]
happened to me as well

**Comment by hakancelikdev** [comment]
Thank you for the report, I will work on it, It would be fixed when publishing the 0.13.0 version of unimport.

**Comment by hakancelikdev** [comment]
@asottile do you have any idea? would you like to help me to solve this issue? I haven't understood why the issue exists.

**Comment by hakancelikdev** [comment]
@asottile Okey I get it, I understand now thank you so much.

I will release a new version to fix this issue.
