### ISSUE TITLE
Register on pre-commit.com

### ISSUE THREAD

**Issue by gregorni** [hakancelikdev/unimport#309]
I'd really like this tool to become listed as supported under https://pre-commit.com/hooks.html.

As there's already a `pre-commit-hooks.yaml` file in the repo, I believe the only step needed is to open a PR with the new line against https://github.com/pre-commit/pre-commit.com/blob/main/all-repos.yaml. I've checked, and all the requirements to add a new repo are fulfilled by unimport.

**Comment by hakancelikdev** [comment]
Thank you, I opened a PR for this in 2020, but it has been deleted, I don't know why. -> https://github.com/pre-commit/pre-commit.com/pull/357

It doesn't matter, I opened it again, thank you again. -> https://github.com/pre-commit/pre-commit.com/pull/911
