### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by gregorni** [hakancelikdev/unimport#310]
Currently, unimport does not work when run in an environment that uses Python 3.12.1. I'm not sure if this is has a technical reason or if it just needs an update for that version. I use unimport a lot for my CI and pre-commit hooks, and would really like to see that version become supported.

**Comment by hakancelikdev** [comment]
Thank you for the issue, I will announce the developments I will work on here.

**Comment by hakancelikdev** [comment]
duplicate issue #302

**Comment by hakancelikdev** [comment]
Now, you can use the 1.2.1 version of unimport.
